[package]
name = "encode-to-image-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.9", features = ["cargo"] }
image = "0.24.6"
rust-lzma = "0.6.0"
